# 1Password-backed environment template. Render it with:
#     ~/.agents/bin/env-bootstrap        (all templates in the repo)
#     ~/.agents/bin/env-pull env.local.tpl
# Reference lines point into a vault — rotate the value there and
# re-render. Config lines below are plain and reviewable.
# Generated by env-adopt from .env.local.
# ─── PostHog (Wizard auto-setup) ─────────────────────────────────────────
# env-check: reviewed NEXT_PUBLIC_POSTHOG_PROJECT_TOKEN — public-prefix-over-TOKEN
NEXT_PUBLIC_POSTHOG_PROJECT_TOKEN=phc_saWAWh3WhLMhycqnfqYMqoZFxv4CvMei4NnU3pGwmSMN
NEXT_PUBLIC_POSTHOG_HOST=https://us.i.posthog.com

# ─── App environment ─────────────────────────────────────────────────────
# local / preview / production — controls Sentry/PostHog sampling & opt-outs
NEXT_PUBLIC_APP_ENV=local

# ─── Backend API ─────────────────────────────────────────────────────────
BJJ_API_URL=https://api.babyjamjam.com

# ─── Sentry (BJJ-155 완료 후 채우기) ──────────────────────────────────────
# 1. sentry.io에서 프로젝트 생성 → DSN 복사
# 2. User Settings → Auth Tokens → project:write, project:releases scope
# env-check: reviewed NEXT_PUBLIC_SENTRY_DSN — public-prefix-over-url-credentials
NEXT_PUBLIC_SENTRY_DSN=https://60ed93f380eea0d46cfc28e80bde9d26@o4510630830276608.ingest.us.sentry.io/4511387543011328
SENTRY_ORG=glint-l0
SENTRY_PROJECT=babyjamjam
SENTRY_AUTH_TOKEN="op://BabyJamJam/BJJ web sentry/SENTRY_AUTH_TOKEN"
